@startuml
class com.example.reuvenbagrut.ProfileFragment {
- ViewPager2 viewPager
- TabLayout tabLayout
- TextView recipesCountText
- TextView followersCountText
- TextView followingCountText
- TextView bioText
- TextView editProfileButton
- FirebaseFirestore db
- FirebaseUser currentUser
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void initializeViews(View)
- void setupViewPager()
- void loadUserData()
+ void onResume()
}


class com.example.reuvenbagrut.adapters.ChatListAdapter {
- Context context
- List<ChatMessage> messages
- OnChatClickListener listener
+ ChatViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ChatViewHolder,int)
+ int getItemCount()
- String formatTime(long)
}


interface com.example.reuvenbagrut.adapters.ChatListAdapter$OnChatClickListener {
~ void onChatClick(ChatMessage)
}

class com.example.reuvenbagrut.adapters.ChatListAdapter$ChatViewHolder {
~ ImageView profileImage
~ TextView userName
~ TextView lastMessage
~ TextView timeText
}

class com.example.reuvenbagrut.activities.ChatDetailActivity {
- MaterialToolbar toolbar
- RecyclerView recyclerView
- TextInputEditText messageInput
- CircularProgressIndicator progressBar
- ChatAdapter chatAdapter
- List<ChatMessage> messages
- String chatId
- String otherUserId
- String currentUserId
- String currentUserName
- String currentUserImage
- FirebaseFirestore db
# void onCreate(Bundle)
- void loadOtherUserData()
- void loadCurrentUserData()
- void loadMessages()
- void sendMessage()
+ boolean onOptionsItemSelected(MenuItem)
}


interface com.example.reuvenbagrut.RecipeApiService {
~ Call<RecipeApiResponse> searchRecipe(String)
}

class com.example.reuvenbagrut.models.Comment {
- String id
- String recipeId
- String userId
- String userName
- String userImage
- String content
- long timestamp
+ String getId()
+ void setId(String)
+ String getRecipeId()
+ void setRecipeId(String)
+ String getUserId()
+ void setUserId(String)
+ String getUserName()
+ void setUserName(String)
+ String getUserImage()
+ void setUserImage(String)
+ String getContent()
+ void setContent(String)
+ long getTimestamp()
+ void setTimestamp(long)
}


class com.example.reuvenbagrut.models.RecipeApiResponse {
- List<RecipeResult> meals
+ List<RecipeResult> getMeals()
+ void setMeals(List<RecipeResult>)
}


class com.example.reuvenbagrut.models.RecipeApiResponse$RecipeResult {
- String idMeal
- String strMeal
- String strCategory
- String strArea
- String strInstructions
- String strMealThumb
- String strTags
- String strYoutube
- String strSource
- String strIngredient1
- String strIngredient2
- String strIngredient3
- String strIngredient4
- String strIngredient5
- String strIngredient6
- String strIngredient7
- String strIngredient8
- String strIngredient9
- String strIngredient10
- String strIngredient11
- String strIngredient12
- String strIngredient13
- String strIngredient14
- String strIngredient15
- String strIngredient16
- String strIngredient17
- String strIngredient18
- String strIngredient19
- String strIngredient20
- String strMeasure1
- String strMeasure2
- String strMeasure3
- String strMeasure4
- String strMeasure5
- String strMeasure6
- String strMeasure7
- String strMeasure8
- String strMeasure9
- String strMeasure10
- String strMeasure11
- String strMeasure12
- String strMeasure13
- String strMeasure14
- String strMeasure15
- String strMeasure16
- String strMeasure17
- String strMeasure18
- String strMeasure19
- String strMeasure20
+ String getIdMeal()
+ String getStrMeal()
+ String getStrCategory()
+ String getStrArea()
+ String getStrInstructions()
+ String getStrMealThumb()
+ String getStrTags()
+ String getStrYoutube()
+ String getStrSource()
+ String getStrIngredient1()
+ String getStrIngredient2()
+ String getStrIngredient3()
+ String getStrIngredient4()
+ String getStrIngredient5()
+ String getStrIngredient6()
+ String getStrIngredient7()
+ String getStrIngredient8()
+ String getStrIngredient9()
+ String getStrIngredient10()
+ String getStrIngredient11()
+ String getStrIngredient12()
+ String getStrIngredient13()
+ String getStrIngredient14()
+ String getStrIngredient15()
+ String getStrIngredient16()
+ String getStrIngredient17()
+ String getStrIngredient18()
+ String getStrIngredient19()
+ String getStrIngredient20()
+ String getStrMeasure1()
+ String getStrMeasure2()
+ String getStrMeasure3()
+ String getStrMeasure4()
+ String getStrMeasure5()
+ String getStrMeasure6()
+ String getStrMeasure7()
+ String getStrMeasure8()
+ String getStrMeasure9()
+ String getStrMeasure10()
+ String getStrMeasure11()
+ String getStrMeasure12()
+ String getStrMeasure13()
+ String getStrMeasure14()
+ String getStrMeasure15()
+ String getStrMeasure16()
+ String getStrMeasure17()
+ String getStrMeasure18()
+ String getStrMeasure19()
+ String getStrMeasure20()
}


class com.example.reuvenbagrut.SignUp {
- MaterialButton signUpButton
- TextInputEditText editTextName
- TextInputLayout nameLayout
- TextView goBack
- ProgressBar progressBar
- FirebaseAuth mAuth
# void onCreate(Bundle)
- void initializeViews()
- void setupClickableSpan()
- void setupClickListeners()
- void performSignUp()
- boolean validateInputs(String,String,String)
- void showLoading(boolean)
- void navigateToHome()
# void onStart()
}


class com.example.reuvenbagrut.HomeFragment {
- {static} String TAG
- RecyclerView recyclerView
- RecipeAdapter recipeAdapter
- SearchView searchView
- FirebaseFirestore db
- FirebaseAuth mAuth
- FirebaseUser currentUser
- SwipeRefreshLayout swipeRefreshLayout
- ChipGroup categoryChipGroup
- ShimmerFrameLayout shimmerLayout
- TextView emptyStateText
- ProgressBar progressBar
- boolean isSearching
- String selectedCategory
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void initViews(View)
- void setupRecyclerView()
- void setupSearchView()
- void setupSwipeRefresh()
- void setupCategoryChips()
- void loadRecipes()
- void searchRecipes(String)
- void updateEmptyState(boolean)
- void showLoading(boolean)
- int getCategoryChipId(String)
+ void onSaveInstanceState(Bundle)
+ void onDestroyView()
+ void onResume()
}


class com.example.reuvenbagrut.LikedRecipesFragment {
- RecyclerView recyclerView
- RecipeAdapter adapter
- SwipeRefreshLayout swipeRefreshLayout
- ShimmerFrameLayout shimmerLayout
- TextView emptyStateText
- FirebaseFirestore db
- FirebaseAuth mAuth
- FirebaseUser currentUser
- ProgressBar progressBar
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void initializeViews(View)
- void setupRecyclerView()
- void setupSwipeRefresh()
- void loadLikedRecipes()
- void updateRecipeList(List<Recipe>)
- void updateEmptyState(boolean)
- void showLoading(boolean)
- void showError(String)
+ void onDestroyView()
}


interface com.example.reuvenbagrut.api.RecipeApiService {
~ Call<RecipeApiResponse> searchRecipes(String)
~ Call<RecipeApiResponse> getRandomRecipes()
~ Call<RecipeApiResponse> getRecipeById(String)
~ Call<RecipeApiResponse> getRecipesByCategory(String)
}

class com.example.reuvenbagrut.models.Chat {
- String id
- List<String> participants
- String lastMessage
- long lastMessageTime
- String lastMessageSenderId
- String lastMessageSenderName
- String lastMessageSenderImage
+ String getId()
+ void setId(String)
+ List<String> getParticipants()
+ void setParticipants(List<String>)
+ String getLastMessage()
+ void setLastMessage(String)
+ long getLastMessageTime()
+ void setLastMessageTime(long)
+ String getLastMessageSenderId()
+ void setLastMessageSenderId(String)
+ String getLastMessageSenderName()
+ void setLastMessageSenderName(String)
+ String getLastMessageSenderImage()
+ void setLastMessageSenderImage(String)
+ void updateLastMessage(ChatMessage)
+ String getOtherParticipantId(String)
}


class com.example.reuvenbagrut.models.ChatMessage {
- String id
- String text
- String senderId
- String senderName
- String senderImage
- long timestamp
+ String getId()
+ void setId(String)
+ String getText()
+ void setText(String)
+ String getSenderId()
+ void setSenderId(String)
+ String getSenderName()
+ void setSenderName(String)
+ String getSenderImage()
+ void setSenderImage(String)
+ long getTimestamp()
+ void setTimestamp(long)
+ String getFormattedTime()
+ String getMessage()
}


class com.example.reuvenbagrut.MainActivity {
- MaterialButton signUpButton
- MaterialButton loginButton
- FirebaseAuth mAuth
- boolean keepSplashScreen
- NavController navController
# void onCreate(Bundle)
- void showLoginScreen()
- void showNavigation()
- void initializeViews()
- void setupClickListeners()
- void setupNavigation()
# void onStart()
}


class com.example.reuvenbagrut.SettingsFragment {
- MaterialButton logoutButton
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
}


class com.example.reuvenbagrut.adapters.RecipeAdapter {
- Context context
- List<Recipe> recipes
- OnRecipeClickListener listener
+ RecipeViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(RecipeViewHolder,int)
+ int getItemCount()
+ void setRecipes(List<Recipe>)
}


interface com.example.reuvenbagrut.adapters.RecipeAdapter$OnRecipeClickListener {
~ void onRecipeClick(Recipe)
}

class com.example.reuvenbagrut.adapters.RecipeAdapter$RecipeViewHolder {
- ShapeableImageView recipeImage
- MaterialTextView recipeName
- MaterialTextView recipeCategory
+ void bind(Recipe)
}


interface com.example.reuvenbagrut.FirebaseCallback {
~ void onSuccess(T)
~ void onError(String)
}

class com.example.reuvenbagrut.adapters.ChatAdapter {
- {static} int VIEW_TYPE_SENT
- {static} int VIEW_TYPE_RECEIVED
- Context context
- List<ChatMessage> messages
- String currentUserId
+ int getItemViewType(int)
+ MessageViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(MessageViewHolder,int)
+ int getItemCount()
- String formatTime(long)
}


class com.example.reuvenbagrut.adapters.ChatAdapter$MessageViewHolder {
~ TextView messageText
~ TextView timeText
~ ImageView profileImage
}

class com.example.reuvenbagrut.models.Recipe {
- String id
- String strMeal
- String strCategory
- String strArea
- String strInstructions
- String strMealThumb
- String strTags
- String strYoutube
- String strSource
- String strCookingTime
- String strServings
- String strDifficultyLevel
- String strAuthorId
- String strAuthor
- String strAuthorImage
- String userId
- String userName
- String userImage
- List<String> ingredients
- String ingredientsString
- List<String> steps
- int likesCount
- boolean isLiked
- long timestamp
- List<String> likedBy
+ {static} Creator<Recipe> CREATOR
+ int describeContents()
+ void writeToParcel(Parcel,int)
+ String getId()
+ void setId(String)
+ String getStrMeal()
+ void setStrMeal(String)
+ String getStrCategory()
+ void setStrCategory(String)
+ String getStrArea()
+ void setStrArea(String)
+ String getStrInstructions()
+ void setStrInstructions(String)
+ String getStrMealThumb()
+ void setStrMealThumb(String)
+ String getStrTags()
+ void setStrTags(String)
+ String getStrYoutube()
+ void setStrYoutube(String)
+ String getStrSource()
+ void setStrSource(String)
+ String getStrCookingTime()
+ void setStrCookingTime(String)
+ String getStrServings()
+ void setStrServings(String)
+ String getStrDifficultyLevel()
+ void setStrDifficultyLevel(String)
+ String getStrAuthorId()
+ void setStrAuthorId(String)
+ String getStrAuthor()
+ void setStrAuthor(String)
+ String getStrAuthorImage()
+ void setStrAuthorImage(String)
+ String getUserId()
+ void setUserId(String)
+ String getUserName()
+ void setUserName(String)
+ String getUserImage()
+ void setUserImage(String)
+ List<String> getIngredients()
+ void setIngredients(List<String>)
+ void setIngredientsString(String)
+ List<String> getSteps()
+ void setSteps(List<String>)
+ int getLikesCount()
+ void setLikesCount(int)
+ boolean isLiked()
+ void setLiked(boolean)
+ long getTimestamp()
+ void setTimestamp(long)
+ List<String> getLikedBy()
+ void setLikedBy(List<String>)
+ boolean isLikedByUser(String)
+ void addLike(String)
+ void removeLike(String)
}


class com.example.reuvenbagrut.adapters.MessageAdapter {
- {static} int VIEW_TYPE_SENT
- {static} int VIEW_TYPE_RECEIVED
- Context context
- List<Message> messages
- String currentUserId
- SimpleDateFormat timeFormat
+ int getItemViewType(int)
+ MessageViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(MessageViewHolder,int)
+ int getItemCount()
}


class com.example.reuvenbagrut.adapters.MessageAdapter$MessageViewHolder {
- MaterialTextView messageText
- MaterialTextView timeText
+ void bind(Message)
}


class com.example.reuvenbagrut.AddRecipeFragment {
- {static} String TAG
- {static} int PICK_IMAGE_REQUEST
- {static} int MAX_IMAGE_DIMENSION
- {static} int JPEG_QUALITY
- boolean isImageChanged
- Uri selectedImageUri
- Bitmap selectedImageBitmap
- View rootView
- EditText recipeNameInput
- EditText ingredientsInput
- EditText instructionsInput
- Button submitButton
- Button addPhotoButton
- ImageView recipeImage
- ProgressBar progressBar
- FirebaseFirestore db
- FirebaseUser currentUser
- StorageReference storageRef
+ void onCreate(Bundle)
- void initializeFirebase()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void initializeViews(View)
- void checkAuthenticationState()
- void setupClickListeners()
- void selectImageFromGallery()
+ void onActivityResult(int,int,Intent)
- void processSelectedImage(Uri)
- boolean isImageFileTooLarge(Uri)
- Bitmap compressImage(Bitmap)
- void validateAndSubmitRecipe()
- void uploadImageAndSaveRecipe(Recipe)
- void saveRecipe(Recipe)
- void handleError(Exception,int)
- void showLoading(boolean)
- void navigateBack()
- void navigateToLogin()
+ void onDestroyView()
}


class com.example.reuvenbagrut.activities.UserProfileActivity {
- ShapeableImageView profileImage
- MaterialTextView userName
- MaterialTextView userEmail
- MaterialTextView recipeCount
- MaterialTextView followersCount
- MaterialButton messageButton
- RecyclerView recipesRecyclerView
- MaterialToolbar toolbar
- FirebaseFirestore db
- FirebaseUser currentUser
- RecipeAdapter recipeAdapter
- List<Recipe> recipes
- String profileUserId
# void onCreate(Bundle)
- void loadUserProfile(String)
- void loadUserRecipes(String)
- void loadFollowersCount(String)
- void setupMessageButton()
}


class com.example.reuvenbagrut.adapters.CommentAdapter {
- Context context
- List<Comment> comments
- OnCommentClickListener listener
+ CommentViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(CommentViewHolder,int)
+ int getItemCount()
- String formatTime(long)
}


interface com.example.reuvenbagrut.adapters.CommentAdapter$OnCommentClickListener {
~ void onCommentClick(Comment)
}

class com.example.reuvenbagrut.adapters.CommentAdapter$CommentViewHolder {
~ ImageView profileImage
~ TextView userName
~ TextView commentText
~ TextView timeText
}

class com.example.reuvenbagrut.models.Message {
- String id
- String senderId
- String senderName
- String content
- long timestamp
+ String getId()
+ void setId(String)
+ String getSenderId()
+ void setSenderId(String)
+ String getSenderName()
+ void setSenderName(String)
+ String getContent()
+ void setContent(String)
+ long getTimestamp()
+ void setTimestamp(long)
}


class com.example.reuvenbagrut.adapters.ProfileTabsAdapter {
+ Fragment createFragment(int)
+ int getItemCount()
}

class com.example.reuvenbagrut.activities.EditProfileActivity {
- ActivityEditProfileBinding binding
- FirebaseFirestore db
- FirebaseAuth auth
- FirebaseStorage storage
- Uri selectedImageUri
- ActivityResultLauncher<String> imagePickerLauncher
# void onCreate(Bundle)
- void setupToolbar()
- void setupImagePicker()
- void loadUserData()
- void setupSaveButton()
- void uploadImageAndSaveProfile(String,String)
- void saveProfile(String,String,String)
+ boolean onOptionsItemSelected(MenuItem)
}


class com.example.reuvenbagrut.UploadedRecipesFragment {
- RecyclerView recyclerView
- RecipeAdapter adapter
- List<Recipe> recipeList
- FirebaseFirestore db
- FirebaseUser currentUser
- SwipeRefreshLayout swipeRefreshLayout
- ShimmerFrameLayout shimmerLayout
- TextView emptyStateText
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void loadUploadedRecipes()
- void updateRecipeList(List<Recipe>)
- void showError(String)
+ void onDestroyView()
}


class com.example.reuvenbagrut.Login {
- TextView goBack
- MaterialButton loginButton
- TextInputEditText editTextPassword
- TextInputLayout passwordLayout
- FirebaseAuth mAuth
- ProgressBar progressBar
# void onCreate(Bundle)
- void initializeViews()
- void setupClickableSpan()
- void setupClickListeners()
- void performLogin()
- boolean validateInputs(String,String)
- void showLoading(boolean)
- void navigateToHome()
# void onStart()
}


class com.example.reuvenbagrut.models.User {
- String id
- String email
- String name
- String profileImageUrl
- String password
- String bio
- String imageUrl
- List<String> followers
- List<String> following
- List<String> likedRecipes
- List<String> uploadedRecipes
+ String getId()
+ void setId(String)
+ String getEmail()
+ void setEmail(String)
+ String getName()
+ void setName(String)
+ String getProfileImageUrl()
+ void setProfileImageUrl(String)
+ String getPassword()
+ void setPassword(String)
+ String getBio()
+ void setBio(String)
+ String getImageUrl()
+ void setImageUrl(String)
+ List<String> getFollowers()
+ void setFollowers(List<String>)
+ List<String> getFollowing()
+ void setFollowing(List<String>)
+ List<String> getLikedRecipes()
+ void setLikedRecipes(List<String>)
+ List<String> getUploadedRecipes()
+ void setUploadedRecipes(List<String>)
+ int getFollowersCount()
+ int getFollowingCount()
+ int getUploadedRecipesCount()
+ boolean isFollowing(String)
+ void addFollower(String)
+ void removeFollower(String)
+ void addFollowing(String)
+ void removeFollowing(String)
+ void addLikedRecipe(String)
+ void removeLikedRecipe(String)
+ void addUploadedRecipe(String)
+ void removeUploadedRecipe(String)
+ String getDisplayName()
+ void setDisplayName(String)
+ String getPhotoUrl()
+ void setPhotoUrl(String)
}


class com.example.reuvenbagrut.activities.SearchActivity {
- {static} String API_KEY
- RecyclerView recyclerView
- RecipeAdapter recipeAdapter
- SearchView searchView
- ShimmerFrameLayout shimmerLayout
- TextView emptyStateText
# void onCreate(Bundle)
- void setupToolbar()
- void initializeViews()
- void setupRecyclerView()
- void setupSearchView()
- void searchRecipes(String)
- void showLoading(boolean)
- void showError(String)
+ boolean onOptionsItemSelected(MenuItem)
# void onDestroy()
}


class com.example.reuvenbagrut.activities.RecipeDetailActivity {
- CollapsingToolbarLayout collapsingToolbar
- MaterialToolbar toolbar
- ShapeableImageView recipeImage
- MaterialTextView recipeCategory
- MaterialTextView recipeIngredients
- MaterialTextView recipeInstructions
- ShapeableImageView userProfileImage
- MaterialTextView userName
- MaterialButton messageCreatorButton
- RecyclerView commentsRecyclerView
- TextInputEditText commentInput
- MaterialButton postCommentButton
- FloatingActionButton favoriteButton
- FirebaseFirestore db
- FirebaseUser currentUser
- CommentAdapter commentAdapter
- List<Comment> comments
- String recipeId
- String recipeUserId
- Recipe recipeObj
# void onCreate(Bundle)
- void initializeViews()
- void openUserProfile()
- void setupFavoriteButton()
- void setupMessageCreatorButton()
- void setupCommentInput()
- void setupPostCommentButton()
- void postComment(String)
- void loadComments()
}


class com.example.reuvenbagrut.activities.SettingsActivity {
# void onCreate(Bundle)
}

class com.example.reuvenbagrut.UserRepository {
- FirebaseAuth auth
- FirebaseFirestore firestore
+ void addUser(User,FirebaseCallback<User>)
+ void getUser(User,FirebaseCallback<User>)
+ void updateUser(String,String,String,Uri,FirebaseCallback<Void>)
+ void deleteUser(FirebaseCallback<Void>)
}


class com.example.reuvenbagrut.activities.ChatActivity {
- MaterialToolbar toolbar
- RecyclerView recyclerView
- TextInputEditText messageInput
- ChatAdapter chatAdapter
- List<ChatMessage> messages
- String otherUserId
- String otherUserName
- String otherUserImage
- String currentUserId
- String chatId
- FirebaseFirestore db
# void onCreate(Bundle)
- String generateChatId(String,String)
- void loadMessages()
- void sendMessage()
}


class com.example.reuvenbagrut.activities.EditRecipeActivity {
- TextInputEditText titleInput
- TextInputEditText descriptionInput
- TextInputEditText ingredientsInput
- TextInputEditText instructionsInput
- TextInputEditText cookingTimeInput
- AutoCompleteTextView difficultyInput
- MaterialButton saveButton
- CircularProgressIndicator progressIndicator
- FirebaseFirestore db
- String recipeId
- Recipe recipe
# void onCreate(Bundle)
- void loadRecipeData()
- void updateUI()
- void saveRecipe()
- void showProgress(boolean)
+ boolean onOptionsItemSelected(MenuItem)
}


class com.example.reuvenbagrut.api.RetrofitClient {
- {static} String BASE_URL
- {static} RetrofitClient instance
- Retrofit retrofit
- RecipeApiService apiService
+ {static} RetrofitClient getInstance()
+ RecipeApiService getApiService()
}


class com.example.reuvenbagrut.ChatFragment {
- {static} String TAG
- RecyclerView recyclerView
- ChatListAdapter adapter
- List<ChatMessage> messages
- String currentUserId
- FirebaseFirestore db
- FirebaseUser currentUser
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void loadChats()
+ void onChatClick(ChatMessage)
}




androidx.fragment.app.Fragment <|-- com.example.reuvenbagrut.ProfileFragment
com.example.reuvenbagrut.adapters.Adapter <|-- com.example.reuvenbagrut.adapters.ChatListAdapter
com.example.reuvenbagrut.adapters.ChatListAdapter +.. com.example.reuvenbagrut.adapters.ChatListAdapter$OnChatClickListener
com.example.reuvenbagrut.adapters.ChatListAdapter +.. com.example.reuvenbagrut.adapters.ChatListAdapter$ChatViewHolder
com.example.reuvenbagrut.adapters.ViewHolder <|-- com.example.reuvenbagrut.adapters.ChatListAdapter$ChatViewHolder
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.activities.ChatDetailActivity
com.example.reuvenbagrut.models.RecipeApiResponse +.. com.example.reuvenbagrut.models.RecipeApiResponse$RecipeResult
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.SignUp
androidx.fragment.app.Fragment <|-- com.example.reuvenbagrut.HomeFragment
androidx.fragment.app.Fragment <|-- com.example.reuvenbagrut.LikedRecipesFragment
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.MainActivity
androidx.fragment.app.Fragment <|-- com.example.reuvenbagrut.SettingsFragment
com.example.reuvenbagrut.adapters.Adapter <|-- com.example.reuvenbagrut.adapters.RecipeAdapter
com.example.reuvenbagrut.adapters.RecipeAdapter +.. com.example.reuvenbagrut.adapters.RecipeAdapter$OnRecipeClickListener
com.example.reuvenbagrut.adapters.RecipeAdapter +.. com.example.reuvenbagrut.adapters.RecipeAdapter$RecipeViewHolder
com.example.reuvenbagrut.adapters.ViewHolder <|-- com.example.reuvenbagrut.adapters.RecipeAdapter$RecipeViewHolder
com.example.reuvenbagrut.adapters.Adapter <|-- com.example.reuvenbagrut.adapters.ChatAdapter
com.example.reuvenbagrut.adapters.ChatAdapter +.. com.example.reuvenbagrut.adapters.ChatAdapter$MessageViewHolder
com.example.reuvenbagrut.adapters.ViewHolder <|-- com.example.reuvenbagrut.adapters.ChatAdapter$MessageViewHolder
android.os.Parcelable <|.. com.example.reuvenbagrut.models.Recipe
com.example.reuvenbagrut.adapters.Adapter <|-- com.example.reuvenbagrut.adapters.MessageAdapter
com.example.reuvenbagrut.adapters.MessageAdapter +.. com.example.reuvenbagrut.adapters.MessageAdapter$MessageViewHolder
com.example.reuvenbagrut.adapters.ViewHolder <|-- com.example.reuvenbagrut.adapters.MessageAdapter$MessageViewHolder
androidx.fragment.app.Fragment <|-- com.example.reuvenbagrut.AddRecipeFragment
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.activities.UserProfileActivity
com.example.reuvenbagrut.adapters.Adapter <|-- com.example.reuvenbagrut.adapters.CommentAdapter
com.example.reuvenbagrut.adapters.CommentAdapter +.. com.example.reuvenbagrut.adapters.CommentAdapter$OnCommentClickListener
com.example.reuvenbagrut.adapters.CommentAdapter +.. com.example.reuvenbagrut.adapters.CommentAdapter$CommentViewHolder
com.example.reuvenbagrut.adapters.ViewHolder <|-- com.example.reuvenbagrut.adapters.CommentAdapter$CommentViewHolder
androidx.viewpager2.adapter.FragmentStateAdapter <|-- com.example.reuvenbagrut.adapters.ProfileTabsAdapter
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.activities.EditProfileActivity
androidx.fragment.app.Fragment <|-- com.example.reuvenbagrut.UploadedRecipesFragment
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.Login
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.activities.SearchActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.activities.RecipeDetailActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.activities.SettingsActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.activities.ChatActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.reuvenbagrut.activities.EditRecipeActivity
com.example.reuvenbagrut.OnChatClickListener <|.. com.example.reuvenbagrut.ChatFragment
androidx.fragment.app.Fragment <|-- com.example.reuvenbagrut.ChatFragment
@enduml